# About NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.

In [1]:
import numpy as np

# NumPy Arrays

NumPy's arrays are more compact than Python lists -- a list of lists as you describe, in Python, would take at least 20 MB or so, while a NumPy 3D array with single-precision floats in the cells would fit in 4 MB. Access in reading and writing items is also faster with NumPy.

NumPy arrays essentially come in two flavors: vectors and matrices. 

**Vectors** are also called 1 dimenssional arrays and have 1 sinlge row.

**Matrices** are also called 2 dimnessional arrays and have two ore more rows and columns.

# Creating NumPy Arrays

There are multiple ways to create NumPy Arrays. They can either be lists or other Python objects that store data using `np.array`, or they can be created on by using `np.arange()`, as well as other methods.

## Converting lists to arrays

In order to convert a list, we must use `np.array` on a list.

In [2]:
# From simple list

my_list = [1,2,3]

# Cast list as array
# Results in one dimentional array
np.array(my_list)

array([1, 2, 3])

Lists containg lists can also be converted into arrays the same way. They become 2d matrices and have a different shape when outputted.

In [3]:
# From list of lists

my_list = [[1,2,3],[4,5,6],[7,8,9]]

#Casting lists as array
#Results in a two dimentional array
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange

`np.arrange()` works just as a Python built-in `range()` function. And, on it's own, creates a 1d array. They can be afterwards remodeled to become matrices.

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,11,2)


array([ 0,  2,  4,  6,  8, 10])

## zeros and ones
Generate arrays of zeros or ones.

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
# 2 = nr. of rows
# 5 = nr. of columns

np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

## linspace

Return evenly spaced numbers over a specified interval.

In [9]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [10]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix.

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Random

Numpy also has lots of ways to create random number arrays.

### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over `[0, 1)`.

In [13]:
np.random.rand(2)

array([0.16206432, 0.06134076])

In [14]:
np.random.rand(5,5)

array([[0.44956387, 0.14329192, 0.1403978 , 0.39781564, 0.137879  ],
       [0.34313082, 0.86622259, 0.90851949, 0.83592413, 0.69204543],
       [0.51962231, 0.72488278, 0.7061898 , 0.27954368, 0.78385555],
       [0.85678311, 0.43824113, 0.65786666, 0.37208436, 0.53818453],
       [0.61305579, 0.47089191, 0.55011498, 0.31499092, 0.93237027]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform.

In [15]:
np.random.randn(2)

array([-1.59894033, -0.96495335])

In [16]:
np.random.randn(3,5)

array([[ 1.39522263,  1.42810052,  0.56251133,  0.93612108, -1.39165625],
       [-0.09709625,  0.73077288,  0.65153919, -0.32582472, -0.21284302],
       [ 0.65611826, -0.69456654, -0.51279843,  0.80970758, -0.30849653]])

### randint

Return random integers from low (inclusive) to high (exclusive).

In [17]:
# Getting a random int

np.random.randint(1,100)

24

In [18]:
# Generating multiple ints

np.random.randint(1,100,10)

array([11, 32, 75, 99, 13, 60, 10, 93, 73, 90])