# NumPy Shapes

As we know, Numpy arrays can have two shapes: 1d and 2d. The shape of an array can be inspected and even changed.

In [1]:
import numpy as np

In [2]:
# Creating a simple array

arr = np.arange(25)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# shape

`np.shape` is an attribute that arrays have, and not a method. It will return basic information about the array, such as the number of rows and columns.

In [4]:
# Vector
# Indicates that it's a one dimentional vector if it isn't

arr.shape

(25,)

# reshape

`np.reshape` allows us to change the shape of our array. We can change our 1d array to a 2d array, with multiple rows and columns. Remember that to have the reshaped array saved, you have to pass its' value to a new array or overwrite the original array.

In [5]:
# Notice the two sets of brackets, it's two dimentional
# It now has 5 rows and 5 columns

arr2 = arr.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

We can even make a 2d array into a 1d array.

In [6]:
arr3 = arr2.reshape(25)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# flatten

The `np.flatten` will make it easier to transform a 2d array into a 1d array.

In [7]:
arr3 = arr2.flatten()
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])