# NumPy Indexing and Selection

Indexing can be done in numpy by using an array as an index. In case of slice, a view or shallow copy of the array is returned but in index array a copy of the original array is returned. Numpy arrays can be indexed with other arrays or any other sequence with the exception of tuples. The last element is indexed by -1 second last by -2 and so on.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


# Bracket Indexing

The simplest way to pick one or some elements of an array looks very similar to python lists.

In [3]:
#Get a value at an index
arr[8]

8

In [4]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [5]:
#Get last value in array
arr[-1]

10

In [6]:
#Get values in a range with a step
arr[1:9:2]

array([1, 3, 5, 7])

# Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast. That means that you may be able to set a value with index range to be equal to a certain value. 

In [7]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


If we decide to slice the array and then broadcast a value to it, it will also change the original array. This is why you have to create a copy of the array using `array_name.copy()`.

In [8]:
# Reset the array
arr = np.arange(0,11)

# Creating a slice of the array
slice_of_arr = arr[0:6]

# Broadcasting 99 to the new slice
slice_of_arr[:] = 99

print("Slice of array: ",slice_of_arr)
print("Original array: ",arr)

Slice of array:  [99 99 99 99 99 99]
Original array:  [99 99 99 99 99 99  6  7  8  9 10]


In [9]:
#To get a copy, need to be explicit
arr = np.arange(0,11)
arr_copy = arr.copy()

arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexing a 2D array

The general format is `arr_2d[row,col]`or `arr_2d[row][col]`.

In [10]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [12]:
# Getting individual element value
arr_2d[1][0]

20

In [13]:
# Getting individual element value 2nd method
arr_2d[1,0]

20

In [14]:
#Indexing column
arr_2d[:,1]

array([10, 25, 40])

In [15]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [16]:
#Get bottom row
arr_2d[-1,:]

array([35, 40, 45])

# Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order.

In [17]:
#Set up matrix
arr2d = np.zeros((10,10))

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
#Length of array
arr_length = arr2d.shape[1]

In [19]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [20]:
# Fancy indexing allows the following
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [21]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

# Conditional Selection

Let's briefly go over how to use brackets for selection based off of comparison operators. We will only get results only when a condition is met.

In [22]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# We can use comparion operators to get boolean values

arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [24]:
# We can assign it to an operator
bool_arr = arr > 4

# Using the boolean operator for selection
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [25]:
# We will only get results where items are over 2
arr[arr>=2]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])