# NumPy Methods

As with lists, we are able to use various methods on arrays. We can sort, delete or append items to an array. We can even merge two arrays. 

In [1]:
import numpy as np

In [2]:
# Lets create two arrays

arr = np.arange(25)
arr2 = arr.reshape(5,5)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Append

`np.append` will add an item to an array at the end of it.

In [5]:
arr = np.append(arr, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [6]:
# Make sure to put .reshape() at the end of the line, otherwise it will make it flat

arr2 = np.append(arr2, [25,26,27,28,29]).reshape(6,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

# Sort

`np.sort` will arrange an array from small to large, as it would in a list.

In [7]:
# Creating a new array for sorting

arrx = np.array([1,2,5,8,124,5688,21,79890,3,4])
arrx

array([    1,     2,     5,     8,   124,  5688,    21, 79890,     3,
           4])

In [8]:
np.sort(arrx)

array([    1,     2,     3,     4,     5,     8,    21,   124,  5688,
       79890])

# Delete

Using `np.delete`, we can delete items that are in an certain index position.

In [9]:
arrx = np.delete(arrx, 5)
arrx

array([    1,     2,     5,     8,   124,    21, 79890,     3,     4])

# Concatenate

We can concatenate two arrays using `np.concatenate()` into a single array.

In [10]:
# Creating two 1d arrays

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [11]:
# Concatenation

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
# Creating 2 arrays, including one 2d

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

# Concatenation
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])