# Operations

We can perform a multitude of operations using arrays.

In [1]:
import numpy as np

In [2]:
# Creating a simple array
arr = np.arange(0,11)

# max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax.

In [3]:
arr.max()

10

In [4]:
arr.min()

0

In [5]:
arr.argmax()

10

In [6]:
arr.argmin()

0

# Arithmetic

In [7]:
# Sum
print(arr + arr)

# Multiply
print(arr * arr)

# Substract
print(arr - arr)

[ 0  2  4  6  8 10 12 14 16 18 20]
[  0   1   4   9  16  25  36  49  64  81 100]
[0 0 0 0 0 0 0 0 0 0 0]


In [8]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\Alex\AppData\Local\Temp/ipykernel_6836/2878212635.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\Alex\AppData\Local\Temp/ipykernel_6836/1360216608.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [10]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

# Universal Array Functions

Numpy comes with many universal array functions, which are essentially just mathematical operations you can use to perform the operation across the array. 

[Documentation](https://numpy.org/doc/stable/reference/ufuncs.html)

In [11]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [12]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [13]:
#Get maximum of an array
#same as arr.max()
np.max(arr) 

10

In [14]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [15]:
np.log(arr)

C:\Users\Alex\AppData\Local\Temp/ipykernel_6836/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])